// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onInternetStatusChange();
void onColumnChange();
void onProblemChange();
void onRandomProblemChange();
void onRowChange();
void onSaveProblemChange();

String internetStatus;
CloudColoredLight column;
CloudColoredLight problem;
CloudColoredLight randomProblem;
CloudColoredLight row;
CloudLight saveProblem;

void initProperties(){

  ArduinoCloud.addProperty(internetStatus, READWRITE, ON_CHANGE, onInternetStatusChange);
  ArduinoCloud.addProperty(column, READWRITE, ON_CHANGE, onColumnChange);
  ArduinoCloud.addProperty(problem, READWRITE, ON_CHANGE, onProblemChange);
  ArduinoCloud.addProperty(randomProblem, READWRITE, ON_CHANGE, onRandomProblemChange);
  ArduinoCloud.addProperty(row, READWRITE, ON_CHANGE, onRowChange);
  ArduinoCloud.addProperty(saveProblem, READWRITE, ON_CHANGE, onSaveProblemChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
